<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\WorkPulse.Application\WorkPulse.Application.csproj" />
    <ProjectReference Include="..\WorkPulse.Integration.Identity\WorkPulse.Integration.Identity.csproj" />
    <ProjectReference Include="..\WorkPulse.Integration.Sql\WorkPulse.Integration.Sql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.OpenApi" Version="3.10.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6f2e0c45-0d3d-4af6-a5dc-7f8f42b4d7db</UserSecretsId>
  </PropertyGroup>

</Project>
